title: Swagger Sample App
description: This is a sample server Pet-store server.
termsOfService: https://swagger.io/terms/
contact:
  name: API Support
  url: https://www.swagger.io/support
  email: support@swagger.io
license:
  name: Apache 2.0
  url: https://www.apache.org/licenses/LICENSE-2.0.html
version: 1.0.1